trigger:
 - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'docker-hub-connection'
    repository: 'robsonaguiarti/kubectl'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 
  
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: 'manifest/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'meu-artefato'
    publishLocation: 'Container'